#!/bin/bash

if [ $# -lt 1 ]
then
    echo "$0 <cFS base>"
    exit 1
fi

CFS_BASE=$1
APP_BASE=${CFS_BASE}/apps

if [ ! -d ${APP_BASE} ]
then
    echo "invalid cFS base (can't find ${APP_BASE}.)"
    exit 2
fi

for protocol in ${APP_BASE}/sbn/modules/protocol/*
do
    b=`basename ${protocol}`
    l="${APP_BASE}/sbn_${b}"
    cp -r "${protocol}" "${l}"
done

for filter in ${APP_BASE}/sbn/modules/filter/*
do
    b=`basename ${filter}`
    l="${APP_BASE}/sbn_f_${b}"
    cp -r "${filter}" "${l}"
done
